### ISSUE TITLE
duplicate and divergent info on landing page

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/data#18]
Some metadata fields appear twice on some landing pages for atmospheric stations, but at least in one case the two values for latitude (and longitude) are different, e.g.
https://meta.icos-cp.eu/ontologies/stationentry/AS/N3

**Comment by mirzov** [comment]
This concerns a technical metadata-resource landing page showing all the statements present about the resource in the RDF database (all the RDF graphs). In the example, duplicate information is present by design, coming from the provisional station database and from the labeling app. When preparing application for labeling, a PI fills a form with station information, but many of the values are pre-filled with the information from the provisional station db. When the application is saved, the form is saved in a separate RDF graph, thus creating the duplicates. The PI can also alter the values, hence, the "divergent info".
