### ISSUE TITLE
netcdf preview scale issue with gcp data

### ISSUE THREAD

**Issue by atverm** [ICOS-Carbon-Portal/data#293]
Fluxes in https://data.icos-cp.eu/portal/#%7B%22route%22:%22preview%22,%22preview%22:%5B%22jYshw7GeDHYCUx7tCfp7JgX6%22%5D%7D have strange scale of PgC m-2 yr-1, with values order 10^-12 to 10^-14. Also data includes missing values as 9.9e+36, which makes preview maps turn completely white. Color scale min and max should be set to exclude 9.9e+36 values always. When you click a point the timeseries plot seems to scale ok.

**Comment by mirzov** [comment]
The issue was related to the netcdf file not having _FillValue metadata entry. New version of the file has been uploaded, where _FillValue is provided (https://meta.icos-cp.eu/objects/GahdRITjT22GGmq_GCi4o_wy), the color scale behaves as expected there. The choice of the units is up to the data producer and up to the elaborated products group, and not an issue with the software.
